# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='atrist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='sont_title',
            new_name='song_title',
        ),
    ]
