# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170309_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favouite',
            field=models.BooleanField(default=False),
        ),
    ]
