# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_is_favouite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favouite',
            new_name='is_favorite',
        ),
    ]
